[project]
name = "noeldeke-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "django>=4.2.27",
    "django-cors-headers>=4.9.0",
    "markdown2>=2.5.4",
    "openai>=2.14.0",
]
